# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('sender_one', models.CharField(max_length=255)),
                ('sender_two', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
