# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20180304_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
