# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
