# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_chat_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sender_one',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
